document.addEventListener('DOMContentLoaded', () => {
  // Find all headings in markdown content
  const markdownContainers = document.querySelectorAll('.markdown-content');
  
  markdownContainers.forEach(container => {
    const headings = container.querySelectorAll('h1, h2, h3, h4, h5, h6');
    
    headings.forEach(heading => {
      // Check if heading already has a link button
      if (heading.querySelector('.heading-link-button')) {
        return; // Skip if link button already exists
      }
      
      // Ensure heading has an ID (should be generated by TOC script)
      if (!heading.id) {
        const text = heading.textContent || '';
        const id = text.toLowerCase()
          .replace(/[^\w\s-]/g, '')
          .replace(/\s+/g, '-');
        heading.id = id;
      }
      
      // Create link icon button
      const linkButton = document.createElement('button');
      linkButton.className = 'heading-link-button';
      linkButton.setAttribute('aria-label', `Copy link to ${heading.textContent}`);
      linkButton.style.cssText = `
        background: none;
        border: none;
        cursor: pointer;
        padding: 0;
        margin-left: 0.5rem;
        opacity: 0;
        transition: opacity 0.2s ease, color 0.2s ease;
        color: rgba(var(--gray), 0.6);
        display: inline-flex;
        align-items: center;
        vertical-align: middle;
      `;
      
      // Link icon SVG
      linkButton.innerHTML = `
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"></path>
          <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"></path>
        </svg>
      `;
      
      // Show link button on heading hover
      heading.addEventListener('mouseenter', () => {
        linkButton.style.opacity = '1';
      });
      
      heading.addEventListener('mouseleave', () => {
        if (!linkButton.classList.contains('copied')) {
          linkButton.style.opacity = '0';
        }
      });
      
      // Copy link on click
      linkButton.addEventListener('click', async (e) => {
        e.preventDefault();
        e.stopPropagation();
        
        const url = window.location.origin + window.location.pathname + '#' + heading.id;
        
        try {
          await navigator.clipboard.writeText(url);
          
          // Show green checkmark
          linkButton.classList.add('copied');
          linkButton.style.color = 'rgb(34, 197, 94)';
          linkButton.style.opacity = '1';
          linkButton.innerHTML = `
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <polyline points="20 6 9 17 4 12"></polyline>
            </svg>
          `;
          
          // Revert after 2 seconds
          setTimeout(() => {
            linkButton.classList.remove('copied');
            linkButton.style.color = 'rgba(var(--gray), 0.6)';
            linkButton.style.opacity = '0';
            linkButton.innerHTML = `
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"></path>
                <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"></path>
              </svg>
            `;
          }, 2000);
        } catch (err) {
          console.error('Failed to copy link:', err);
        }
      });
      
      // Append link button to heading
      heading.appendChild(linkButton);
    });
  });
});